- name: "Deploy Policies, Groups and Users"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws-credentials.yml
    - vars/aws-arn.yml

  tasks:

  - include: tasks/create-policy.yml

  - include: tasks/create-group.yml

  - include: tasks/create-user.yml

